### ISSUE TITLE
real-time add data,the graph doesn't right.

### ISSUE THREAD

**Issue by joy-chen** [appsthatmatter/GraphView#449] opened 2016-11-24 05:40 UTC
![screenshot_20161124-133607](https://cloud.githubusercontent.com/assets/3357420/20587837/8ebbd8ce-b24b-11e6-993c-c058198cf1cb.jpg)
please check the photo
it just show up on MTK device.

**Comment by jjoe64** [comment] 2016-11-24 10:39
is there a way you can give me the source code so that I can exactly test this and fix it?

**Comment by joy-chen** [comment] 2016-11-25 07:30
@jjoe64 I just install the GraphView demo in MTK device, [source](https://github.com/jjoe64/GraphView-Demos/blob/master/app/src/main/java/com/jjoe64/graphview_demos/categories/RealtimeFragment.java)

**Comment by jjoe64** [comment] 2016-11-25 20:16
need some device to reproduce it...

**Comment by joy-chen** [comment] 2016-12-08 07:30
Hi, this could be reproduce on any devices using MTK cpu.

**Comment by Alwaysso** [comment] 2017-11-30 07:19
How to solve the problem

**Comment by appsthatmatter** [comment] 2018-04-19 10:54
related to #499

**Comment by appsthatmatter** [comment] 2018-04-20 06:44
@joy-chen @Alwaysso 
I did an update, but since I cannot reproduce the problem I ask you to check if it's looking good now, on the devices? I updated the GraphView Demos app in Google Play. So could you please verify?

**Comment by appsthatmatter** [comment] 2018-04-23 09:42
should be fixed

**Closed by appsthatmatter** 2018-04-23 09:42 UTC
Labels: prio-high, type-bug
