### ISSUE TITLE
Automatic setting of X Boundaries when using TimeSeries

### ISSUE THREAD

**Issue by michael-paulus** [appsthatmatter/GraphView#458] opened 2016-12-19 19:42 UTC
Hi Jonas, thanks for this awesome library.
One thing though does not work as I understood it should.
I add two TimeSeries to a Linegraph, and the X Axis does not adjust itself to the proper width of all series combined, e.g. there is a series starting at 10:00 and ending at 10:10, the other starting at 10:12, ending at 10:13. The graph will seemingly randomly chose its width, sometimes not even showing the second series at all. If you're interested, I can send you the code I'm using.

**Comment by sidlgor** [comment] 2016-12-23 16:11
Hi Jonas, I have about the same problem. The autoscaling of the X-axis does not seems to work correctly.
I was able to reproduce the problem with just a small timeseries of 4 points.
Following points should scale the X-axis between 0 and 14. However it auto-scales between 0 and 8.
            points[0] = new DataPoint(0, 250);
            points[1] = new DataPoint(1, 700);
            points[2] = new DataPoint(2, 50);
            points[3] = new DataPoint(14, 200);
When changing the X-coordinate of the last point up to 19, it will still autoscales between 0 an 8. Then moving to X=20 autoscaling jumps to the correct 0 to 20.
When using viewport manual XAxis bounds, scaling is correct!

**Comment by appsthatmatter** [comment] 2018-01-31 11:31
closed, because too old. If the problem still exists, please reopen a new ticket.

**Closed by appsthatmatter** 2018-01-31 11:31 UTC
